# Site settings
name: Samuel Yip # your name
header-image: images/home-bg.jpg # image in header
tagline: "Technology | Design | Education" # your personal tagline 
city: Singapore # your city
country: Singapore # your country
email: samyipsh@gmail.com # your email address
#twitter_name: timklapdor # your twitter handle
github_name:  samyipsh # your github name
baseurl: "/resume" #base url
url: # "http://yourdomain.com"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
